name: Run Python Script at Specific Times

on:
  schedule:
    # Monday to Friday (PST 7AM - 11PM → UTC 3PM - 7AM next day)
    - cron: "*/20 14-23,0-6 * * 1-5"

    # Saturday (PST 8AM - 6PM → UTC 4PM - 2AM next day)
    - cron: "*/20 15-23,0-1 * * 6"

    # Sunday (PST 8AM - 11PM → UTC 4PM - 7AM next day)
    - cron: "*/20 15-23,0-6 * * 0"

  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Modify if necessary

      - name: Set up Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

      - name: Run Python Script
        run: python rsf_occupancy_collector.py
        env:
          DENSITY_API_KEY: ${{ secrets.DENSITY_API_KEY }}
          DENSITY_API_URL: ${{ secrets.DENSITY_API_URL }}
          MAX_CAPACITY: ${{ secrets.MAX_CAPACITY }}
          SPREADSHEET_NAME: ${{ secrets.SPREADSHEET_NAME }}
