name: Run Python Script at Specific Times

on:
  schedule:
    # Monday to Friday (PST 7AM - 11PM → UTC 3PM - 7AM next day)
    - cron: "0,20 15-23,0-7 * * 1-5"

    # Saturday (PST 8AM - 6PM → UTC 4PM - 2AM next day)
    - cron: "0,20 16-23,0-2 * * 6"

    # Sunday (PST 8AM - 11PM → UTC 4PM - 7AM next day)
    - cron: "0,20 16-23,0-7 * * 0"

  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Modify if necessary

      - name: Run Python Script
        run: python your_script.py  # Replace with your actual script
